### ISSUE TITLE
Possible other output formats?

### ISSUE THREAD

**Issue by nomo-nomad** [heckj/crawl2pdf#1]
Have you looked into creating a "webarchive" output format -- copy and write the css, javascript, html and images or other media to disk -- vs creating a pdf. I'm trying to automate the process of saving a local "copy" of any website. My javascript experience is weak but I'm strongly considering trying to implement something similar.

**Comment by heckj** [comment]
@nomo-nomad I haven't gone in that direction. In this case, I specifically wanted/needed PDFs - primarily for their portability and markup. I had been doing that thing were you open a load of pages into tabs and then saving each one to PDF from the browser.

I don't know the web-archive format, but I'd be tempted to lean into something that already knows it and automating that. Safari does a reasonable job of saving it out - that automation is probably mostly Accessibility enabled on a Mac. In the past for things like this (replicating and storing a copy of content), honestly I've just replicated the site with `wget`.

**Comment by nomo-nomad** [comment]
@heckj oh geez. I can't believe I didn't think to give `wget` a shot. Have you shared anything like a blog post or video on your process? I'm gonna see how far I can get with it now. Thanks a bunch for taking the time. 😁

**Comment by heckj** [comment]
No, nothing on either front like that. `wget --mirror` was about as complex as it got for me for ages. I didn't need this chromium-crawler level of interaction for ages, but the particular target I was trying to pull down into PDFs started using JavaScript extensively to construct their DOMs and links, so simple mirrors weren't going to cut it - plus I wanted it in PDF format explicitly.
